trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npx playwright install --with-deps
    displayName: 'Install Playwright Browsers'

  - script: npm run start &
    displayName: 'Start Application'

  - script: npx wait-on http://localhost:3000
    displayName: 'Wait for Application to be Ready'

  - script: npm run test:e2e
    displayName: 'Run Playwright Tests'

  - script: npx playwright show-report
    displayName: 'Generate Playwright Report'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'playwright-report'
      pathToPublish: 'playwright-report/'
